# Flutter: 3.3.4      old: 3.0.1
# Dart: 2.18.2        old: 2.17.1
# Java: 17    gradle.properties (org.gradle.java.home)

# https://www.figma.com/file/7VGoqckp0hWyFNaBQxmUTU/022---English-App-(BigBango)?node-id=0%3A1

name: app         # BigBango
description: A system to learn languages
#repository: https://github.com/...

publish_to: 'none'

version: 1.0.1+1


environment:
  sdk: ">=2.18.0"             # null Safety : 2.12.0
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter

  import_sorter: ^4.6.0
  flutter_launcher_icons: ^0.11.0

  flutter_localizations:
    sdk: flutter

  device_preview: ^1.1.0
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.8
  device_info_plus: ^8.0.0
  platform_device_id: ^1.0.1
  permission_handler: ^10.2.0
  pull_to_refresh: ^2.0.0
  material_dialogs: ^1.1.4
  flutter_spinkit: ^5.1.0
  awesome_notifications: 0.6.21                 # can not upgrade to new, occur error
  popover: ^0.2.8
  numberpicker: ^2.1.1
  chewie: ^1.4.0
  video_player: ^2.5.1
  dio: ^4.0.6
  im_animations: ^0.1.2                          # ColorSonar
  animate_do: ^3.0.2
  animator: ^3.2.0
  pinput: 2.2.21
  stop_watch_timer: ^2.0.0
  dropdown_button2: ^1.9.2
  persian_modal_date_picker: ^0.0.3              # add: useRootNavigator: true, to source code
  modal_bottom_sheet: ^2.1.2
  extended_sliver: ^2.1.3
  jwt_decoder: ^2.0.1
  dart_jsonwebtoken: ^2.6.4
  android_sms_retriever: ^1.3.3
  shamsi_date: ^1.0.1
  simple_html_css: ^4.0.0
  just_audio: ^0.9.31
  image_picker: ^0.8.6+1
  firebase_messaging: ^14.2.1                   # old: 14.0.4
  firebase_core: ^2.4.1                         # old: 2.1.1
  toggle_switch: ^2.0.1
  flutter_sound: ^9.2.13
  mask_input_formatter: ^0.0.3
  switch_tab: ^0.1.3
  # last size: v7a-release.apk (9.9MB)


  iris_tools:
    git: https://github.com/ali-1989/IrisTools.git
  iris_db:
    git: https://github.com/ali-1989/IrisDB.git
  iris_pic_editor:
    git: https://github.com/ali-1989/IrisPicEditor.git
  #iris_audio_visualizer:
    #path: ../thParty/audio_visualizer-master


  # packages that for iOS needs additional code:
  # https://pub.dev/packages/just_audio#ios
  # https://pub.dev/packages/url_launcher#ios
  # https://pub.dev/packages/permission_handler
  # https://pub.dev/packages/awesome_notifications#-configuring-ios
  # https://pub.dev/packages/video_player#ios
  # https://pub.dev/packages/image_picker#ios

# packages that for Android needs additional code:
  # https://pub.dev/packages/url_launcher#android
  # https://pub.dev/packages/permission_handler
  # https://pub.dev/packages/awesome_notifications#-configuring-android
  # https://pub.dev/packages/pinput#android

dependency_overrides:
  path: ^1.8.3
  ffi: ^2.0.1
  shamsi_date: ^1.0.1
  image: ^4.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  # Image.asset('assets/images/x.jpg')
  assets:
    - assets/images/
    - assets/audio/

  #style: normal  # normal, italic
  #weight: 500
  fonts:
    - family: shabnam
      fonts:
      - asset: assets/fonts/ShabnamMediumFD.ttf
    - family: shabnam_bold
      fonts:
      - asset: assets/fonts/ShabnamBoldFD.ttf



flutter_icons:
  image_path: "dep/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true


import_sorter:
  emojis: false
  comments: false


## flutter pub run import_sorter:main
## flutter pub run flutter_launcher_icons:main


# caret sign:
# ^0.1.2 is the same as '>=0.1.2 <0.2.0'
# ^1.2.3 would be the same as '>=1.2.3 <2.0.0'
# if not use caret sign , force download/use that version.
