# Flutter: 3.10.0      old: 3.7.2
# Dart: 3.0.0        old: 2.19.1
# Java: 17

# https://www.figma.com/file/7VGoqckp0hWyFNaBQxmUTU/022---English-App-(BigBango)?node-id=0%3A1

name: app         # BigBango
description: A system to learn languages
#repository: https://github.com/...

publish_to: 'none'

version: 1.0.3+1


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter

  import_sorter: ^4.6.0
  flutter_launcher_icons: ^0.13.1

  flutter_localizations:
    sdk: flutter

  #device_preview: ^1.1.0
  cupertino_icons: ^1.0.5
  #community_material_icon: ^5.9.55      # https://materialdesignicons.com/
  device_info_plus: ^9.0.2
  platform_device_id: ^1.0.1
  permission_handler: ^10.3.0            # NoWeb
  video_player: ^2.6.1
  chewie: ^1.5.0
  http: ^1.0.0
  dio: ^5.2.1+1
  connectivity_plus: ^4.0.1
  url_launcher: ^6.1.11
  material_dialogs: ^1.1.4
  awesome_notifications: 0.6.21                 # can not upgrade to new, occur error, 0.6.21
  popover: ^0.2.8+2
  flutter_spinkit: ^5.2.0
  stop_watch_timer: ^2.0.0
  iris_notifier: ^0.0.4
  numberpicker: ^2.1.2
  pull_to_refresh: ^2.0.0
  image_picker: ^0.8.9
  toggle_switch: ^2.1.0
  firebase_messaging: ^14.6.3
  firebase_core: ^2.14.0
  im_animations: ^0.1.2                          # ColorSonar
  animate_do: ^3.0.2
  animator: ^3.3.0
  pinput: ^2.2.31
  dropdown_button2: ^2.1.0
  persian_modal_date_picker: ^0.0.3              # add: useRootNavigator: true, to source code
  extended_sliver: ^2.1.3
  jwt_decoder: ^2.0.1
  dart_jsonwebtoken: ^2.8.2
  android_sms_retriever: ^1.3.3
  shamsi_date: ^1.0.1
  simple_html_css: ^4.0.0
  audio_session: any
  logger: any
  flutter_sound: ^9.2.13
  mask_input_formatter: ^0.0.3
  switch_tab: ^0.1.3
  just_audio: ^0.9.34
  # last size: v7a-release.apk (9.9MB)


  iris_tools:
    git: https://github.com/ali-1989/IrisTools.git
  iris_db:
    git: https://github.com/ali-1989/IrisDB.git
  iris_pic_editor:
    git: https://github.com/ali-1989/IrisPicEditor.git
  iris_runtime_cache:
    git: https://github.com/ali-1989/irisRuntimeCache.git
  iris_route:
    git: https://github.com/ali-1989/iris_route.git


dependency_overrides:
  intl: 0.18.1    # awesome_notifications, flutter_localizations
  win32: 4.1.4    # file_picker, wakelock_windows
  shamsi_date: 1.0.1
  collection: ^1.17.2
  http: ^1.0.0
  file: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  # Image.asset('assets/images/x.jpg')
  assets:
    - assets/images/
    - assets/locales/
    - assets/audio/


  #style: italic  weight: 700
  fonts:
    - family: shabnam
      fonts:
      - asset: assets/fonts/ShabnamMediumFD.ttf
    - family: shabnam_bold
      fonts:
      - asset: assets/fonts/ShabnamBoldFD.ttf



flutter_icons:
  image_path: "#Dep/app_icon.jpg"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
    icon_size: 96


import_sorter:
  emojis: false
  comments: false


  # ** packages that for iOS needs additional code:
  # https://pub.dev/packages/just_audio#ios
  # https://pub.dev/packages/url_launcher#ios
  # https://pub.dev/packages/permission_handler
  # https://pub.dev/packages/awesome_notifications#-configuring-ios
  # https://pub.dev/packages/video_player#ios
  # https://pub.dev/packages/image_picker#ios
  # https://pub.dev/packages/flutter_local_auth_invisible#ios-integration

  # ** packages that for Android needs additional code:
  # https://pub.dev/packages/url_launcher#android
  # https://pub.dev/packages/permission_handler
  # https://pub.dev/packages/awesome_notifications#-configuring-android
  # https://pub.dev/packages/pinput#android


## flutter pub run import_sorter:main
## flutter pub run flutter_launcher_icons

# import '[^pd/]

# caret sign:
# ^0.1.2 is the same as '>=0.1.2 <0.2.0'
# ^1.2.3 would be the same as '>=1.2.3 <2.0.0'
# if not use caret sign , force download/use that version